# core/adapter/__init__.py
# core/cache/__init__.py
# core/conversation/__init__.py
# core/events/builders/__init__.py
# core/events/history_fetcher/__init__.py
# core/events/models/__init__.py
# core/events/processors/__init__.py
# core/rate_limiter/__init__.py
# core/socket_io/__init__.py
# core/utils/__init__.py
